src/home/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomeView,
    PostDetailView,
    PostEditView,
    PostDeleteView,
    PostLikeView,
    PostUnlikeView,
    PostCommentView,
    NetworkView,
    ViewAllConnectionsView,
    CommentReplyView,
    CommentDeleteView,
)


urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_view'),
    path(
        'edit/<int:id>',
        login_required(PostEditView.as_view()),
        name='post_edit_view'
    ),
    path(
        'post/<int:id>',
        login_required(PostDetailView.as_view()),
        name='post_detail_view'
    ),
    path(
        'delete/post/<int:id>',
        login_required(PostDeleteView.as_view()),
        name='post_delete_view'
    ),
    path(
        'post/like/<int:id>',
        login_required(PostLikeView.as_view()),
        name='post_like_view'
    ),
    path(
        'post/unlike/<int:id>',
        login_required(PostUnlikeView.as_view()),
        name='post_unlike_view'
    ),
    path(
        'post/comment/<int:id>',
        login_required(PostCommentView.as_view()),
        name='post_comment_view'
    ),
    path(
        'comment/reply/<int:id>',
        login_required(CommentReplyView.as_view()),
        name='reply_comment_view'
    ),
    path(
        'comment/delete/<int:id>',
        login_required(CommentDeleteView.as_view()),
        name='comment_delete_view'
    ),
    path(
        'my-network/',
        login_required(NetworkView.as_view()),
        name='network_view'
    ),
    path(
        'view-all-connections/',
        login_required(ViewAllConnectionsView.as_view()),
        name='view_all_connections_view'
    ),
]

src/linkedin_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('user.urls')),
]

urlpatterns.extend(
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
)

src/home/models.py
from django.db import models
from django.contrib.auth import get_user_model
from crum import get_current_user

User = get_user_model()


# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=400, null=True, blank=True)
    media = models.FileField(upload_to='post_images', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        user = get_current_user()

        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user

        super(Post, self).save(*args, **kwargs)

    @property
    def likes_count(self):
        return self.like_set.count()

    @property
    def comments_count(self):
        return self.comment_set.count()

    class Meta:
        ordering = ['-updated_on']


class Comment(models.Model):
    text = models.CharField(max_length=140)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        user = get_current_user()

        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user

        super(Comment, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-commented_on']

    def get_comments(self):
        return Comment.objects.filter(parent=self)


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(True)

    def save(self, *args, **kwargs):
        user = get_current_user()

        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user

        super(Like, self).save(*args, **kwargs)


class Connection(models.Model):
    user1 = models.ForeignKey(
        User,
        related_name='connection_user',
        on_delete=models.CASCADE,
        editable=False
    )
    user2 = models.ForeignKey(
        User,
        related_name='connection_connection',
        on_delete=models.CASCADE
    )
    is_connected = models.BooleanField(default=False)
    is_requested = models.BooleanField(default=True)
    requested_on = models.DateTimeField(auto_now=True)
    connected_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user1} ~ {self.user2}"

    def save(self, *args, **kwargs):
        user = get_current_user()

        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user

        super(Connection, self).save(*args, **kwargs)

src/templates/components/comment.html
<div style="margin-left: 10%">
  {% if reply_comment.user == user %}
  <button
    type="button"
    style="
      border: none;
      background: transparent;
      float: right;
      position: relative;
      top: 35px;
      right: 8px;
    "
    data-toggle="modal"
    data-target="#deleteComment_{{ reply_comment.pk }}"
  >
    <i class="material-icons sidebar_topAvatar"> delete </i>
  </button>
  <div id="deleteComment_{{reply_comment.pk}}" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title delete-title">Delete Post?</div>
          <div class="delete-post-text">
            Are you sure you want to delete this comment from post?
          </div>
        </div>
        <div class="modal-body">
          <form
            method="POST"
            style="display: inline; float: right"
            action="{% url 'comment_delete_view' reply_comment.pk %}"
          >
            {% csrf_token %}

            <a class="btn btn-sm btn-info" data-dismiss="modal">Cancel</a>
            <button type="submit" style="border: none; background: none">
              Delete
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <div
    style="
      display: flex;
      flex-direction: row;
      padding: 4px 16px;
      background: rgba(0, 0, 0, 0.1);
      width: 100%;
      border-top-left-radius: 8px;
      border-top-right-radius: 8px;
      border: 1px solid rgba(0, 0, 0, 0.2);
      border-bottom: none;
    "
  >
    <a
      href="{% url 'profile_view' reply_comment.user.username %}"
      style="align-self: center"
    >
      {% if reply_comment.user.picture %}
      <img
        style="height: 40px; width: 38px; border-radius: 50% !important"
        src="{{ reply_comment.user.picture.url }}"
      />
      {% else %}<i
        style="
          text-decoration: none;
          text-transform: none;
          color: rgba(0, 0, 0, 0.9);
          font-size: 40px;
          border-radius: 50% !important;
        "
        class="material-icons sidebar_topAvatar"
      >
        account_circle
      </i>
      {% endif %}
    </a>
    <div style="margin-left: 8px">
      <div>{{ reply_comment.user.username }}</div>
      <div>{{ reply_comment.user.bio }}</div>
    </div>
  </div>
  <div
    style="
      padding: 4px 16px;
      background: rgba(0, 0, 0, 0.1);
      border: 1px solid rgba(0, 0, 0, 0.2);
      border-top: none;
      border-bottom-left-radius: 8px;
      border-bottom-right-radius: 8px;
    "
  >
    {{ reply_comment.text }}
  </div>
  <button
    onclick="handleReply({{reply_comment.id}})"
    style="
      margin-top: 4px;
      background: none;
      border: none;
      color: rgba(0, 0, 0, 0.6);
    "
  >
    Reply
  </button>

  <div id="reply-form-{{reply_comment.id}}" style="display: none">
    <form
      method="post"
      action="{% url 'reply_comment_view' reply_comment.id %}"
      class="mt-3"
    >
      {% csrf_token %}
      <textarea
        name="comment_text"
        placeholder="Post Comment..."
        style="outline: none; border: none"
        maxlength="140"
      ></textarea>
      <div>
        <button
          type="button"
          onclick="handleCancel({{reply_comment.id}})"
          class="btn btn-light border btn-sm"
        >
          Cancel
        </button>
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
      </div>
    </form>
  </div>
  {% for reply_comment in reply_comment.get_comments %}
  {% include 'components/comment.html'%}
  {% endfor %}
</div>

src/templates/components/create_post.html
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">Create Post</h4>
      <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
          <div class="col-sm-8">
            <textarea
              type="text"
              rows="6"
              name="text"
              class="form-control form-control-sm"
              placeholder="What do you want to talk about?"
              maxlength="400"
            ></textarea>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-8">
            <input
              type="file"
              name="media"
              accept="image/*,video/*,text/*"
            />
          </div>
        </div>

        <div>
          <button class="btn btn-sm btn-primary">Post</button>
        </div>
      </form>
    </div>
  </div>
</div>

src/templates/components/edit_profile.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} 
  {% for field in form %}
  {% if field.label != "Picture" and field.label != "Email"  %}
  <div class="form-group row">
    <label
      class="
        col-sm-2 col-form-label col-form-label-sm
        text-md-right
        font-weight-bolder
      "
      for="{{ field.auto_id }}"
      >{{ field.label }}</label
    >
    <div class="col-sm-8">
      {{ field }}
      <small id="passwordHelpBlock" class="form-text text-muted">
        {{ field.help_text }}
      </small>
      <div class="invalid-feedback">{{ field.errors }}</div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
  <div class="offset-md-2 my-1">
    <button class="btn btn-sm btn-primary">Submit</button>
  </div>
</form>

src/templates/components/edit_profile_photo.html
<form
  method="POST"
  enctype="multipart/form-data"
  action="{% url 'change_user_profile_photo' %}"
>
  {% csrf_token %}
  <div class="form-group row">
    <div class="col-sm-8">
      {% if request.user.picture %}
      <div style="padding-bottom: 8px">
        <div>Current Image:<br /></div>
        <img
          style="display: block; width: 40%"
          src="{{ request.user.picture.url}}"
        />
      </div>
      {% endif %}
      <input type="file" name="picture" accept="image/*" />
      <div class="invalid-feedback"></div>
    </div>
  </div>

  <div>
    <button class="btn btn-sm btn-primary" value="update">Update</button>
    <button
      type="submit"
      class="btn btn-sm btn-danger"
      name="remove_photo"
      value="remove_photo"
    >
      Remove Photo
    </button>
  </div>
</form>

src/templates/components/header.html
{% load static %}
<div class="header">
  <div class="header_left">
    <a href="{% url 'home_view' %}">
      <img src="{% static 'img/Linkedin-Logo-small.png' %}" />
    </a>
    <form
      method="GET"
      class="header_search"
      action="{% url 'search_profile_view' %}"
    >
      <i class="material-icons"> search </i>
      <input type="text" name="query" placeholder="Search" />
    </form>
  </div>

  <div class="header_right">
    <a href="{% url 'home_view' %}">
      <div class="headerOption">
        <i class="material-icons headerOption_icon"> house </i>
        <h3>Home</h3>
      </div>
    </a>
    <a href="{% url 'network_view' %}">
      <div class="headerOption">
        <i class="material-icons headerOption_icon"> supervisor_account </i>
        <h3>My Network</h3>
      </div>
    </a>
    <div class="headerOption">
      <i class="material-icons headerOption_icon"> business_center </i>
      <h3>Jobs</h3>
    </div>
    <div class="headerOption">
      <i class="material-icons headerOption_icon"> chat </i>
      <h3>Messaging</h3>
    </div>
    <div class="headerOption">
      <i class="material-icons headerOption_icon"> notifications </i>
      <h3>Notifications</h3>
    </div>
    <a href="{% url 'profile_view' request.user.username %}">
      <div class="headerOption">
        {% if request.user.picture %}
        <img src="{{ request.user.picture.url }}" class="headerOption_icon" />
        {% else %}
        <i class="material-icons headerOption_icon"> account_circle </i>
        {% endif %}
        <h3>Me</h3>
      </div>
    </a>
    <form method="POST" action="{% url 'signout_view' %}">
      {% csrf_token %}
      <button
        class="headerOption"
        style="background: none; border: none; margin: 0; padding: 0"
      >
        <i class="material-icons headerOption_icon"> logout </i>
        <h3>Sign Out</h3>
      </button>
    </form>
  </div>
</div>
<div
  class="bottom-nav"
  style="
    display: flex;
    position: fixed;
    bottom: 0;
    width: 100%;
    justify-content: space-between;
    background: #fff;
  "
>
  <a href="{% url 'home_view' %}">
    <div class="headerOption">
      <i class="material-icons headerOption_icon"> house </i>
      <h3>Home</h3>
    </div>
  </a>
  <a href="{% url 'network_view' %}">
    <div class="headerOption">
      <i class="material-icons headerOption_icon"> supervisor_account </i>
      <h3>My Network</h3>
    </div>
  </a>
  <div class="headerOption">
    <i class="material-icons headerOption_icon"> business_center </i>
    <h3>Jobs</h3>
  </div>
  <div class="headerOption">
    <i class="material-icons headerOption_icon"> chat </i>
    <h3>Messaging</h3>
  </div>
  <div class="headerOption">
    <i class="material-icons headerOption_icon"> notifications </i>
    <h3>Notifications</h3>
  </div>
  <a href="{% url 'profile_view' request.user.username %}">
    <div class="headerOption">
      {% if request.user.picture %}
      <img src="{{ request.user.picture.url }}" class="headerOption_icon" />
      {% else %}
      <i class="material-icons headerOption_icon"> account_circle </i>
      {% endif %}
      <h3>Me</h3>
    </div>
  </a>
  <form method="POST" action="{% url 'signout_view' %}">
    {% csrf_token %}
    <button
      class="headerOption"
      style="background: none; border: none; margin: 0; padding: 0"
    >
      <i class="material-icons headerOption_icon"> logout </i>
      <h3>Sign Out</h3>
    </button>
  </form>
</div>

src/templates/components/post_detail.html
<div class="post">
  <div class="post_header">
    <a
      href="{% url 'profile_view' post.post.user.username %}"
      style="align-self: center"
    >
      {% if post.post.user.picture %}
      <img src="{{ post.post.user.picture.url }}" />
      {% else %}<i class="material-icons sidebar_topAvatar"> account_circle </i>
      {% endif %}
    </a>
    <div class="post_info">
      <a
        style="
          text-decoration: none;
          text-transform: none;
          color: rgba(0, 0, 0, 0.9);
        "
        href="{% url 'profile_view' post.post.user.username %}"
      >
        <div>
          {{ post.post.user.first_name }} {{ post.post.user.last_name }}
        </div>
        {% if post.post.user.headline and post.post.user.headline.strip %}
        <div class="headline">
          {{ post.post.user.headline }}
        </div>
        {% endif %}
      </a>
    </div>
    {% if post.post.user.username == request.user.username %}
    <div class="post-options">
      <button
        type="button"
        style="border: none; background: none"
        data-toggle="modal"
        data-target="#editPost_{{ post.post.pk }}"
      >
        <i class="material-icons sidebar_topAvatar"> edit </i>
      </button>
      <div id="editPost_{{ post.post.pk }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Edit Post</h4>
              <button type="button" class="close" data-dismiss="modal">
                &times;
              </button>
            </div>
            <div class="modal-body">
              <form
                method="POST"
                enctype="multipart/form-data"
                action="{% url 'post_edit_view' post.post.id %}"
              >
                {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-8">
                    <input
                      type="text"
                      name="text"
                      class="form-control form-control-sm"
                      placeholder="What do you want to talk about?"
                      maxlength="400"
                      value="{% if post.post.text %}{{post.post.text}}{% endif %}"
                      id="id_text"
                    />
                    <div class="invalid-feedback"></div>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-sm-8">
                    {% if post.post.media %}
                    <div style="padding-bottom: 8px">
                      <div>Current Media:<br /></div>
                      {% if post.post.media %}
                      <embed
                        style="width: 95%; height: 100%"
                        src="{{post.post.media.url}}"
                        type="{{post.file_type}}"
                      />{% endif %}
                      <input type="checkbox" name="remove_media" /> Remove Media
                    </div>
                    {% endif %}
                    <input
                      type="file"
                      name="media"
                      accept="image/*,video/*,text/*"
                      id="id_image"
                    />
                    <div class="invalid-feedback"></div>
                  </div>
                </div>

                <div class="my-1">
                  <button class="btn btn-sm btn-primary">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <button
        type="button"
        style="border: none; background: none"
        data-toggle="modal"
        data-target="#deletePost_{{ post.post.pk }}"
      >
        <i class="material-icons sidebar_topAvatar"> delete </i>
      </button>
      <div id="deletePost_{{post.post.pk}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <div class="modal-title delete-title">Delete Post?</div>
              <div class="delete-post-text">
                Are you sure you want to permanently remove this post from
                LinkedIn Clone?
              </div>
            </div>
            <div class="modal-body">
              <form
                method="POST"
                style="display: inline; float: right"
                action="{% url 'post_delete_view' post.post.pk %}"
              >
                {% csrf_token %}

                <a class="btn btn-sm btn-info" data-dismiss="modal">Cancel</a>
                <button type="submit" style="border: none; background: none">
                  Delete
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>

  <a
    style="display: block"
    class="post-link"
    href="{% url 'post_detail_view' post.post.pk %}"
  >
    {% if post.post.text %}
    <div class="post_body">
      <p style="max-width: 90%; overflow-wrap: anywhere">{{ post.post.text}}</p>
    </div>
    {% endif %} {% if post.post.media %} {% if post.file_type != 'others' %}
    <embed
      style="width: fit-content; height: 100%; max-width: 95%"
      src="{{post.post.media.url}}"
      type="{{post.file_type}}"
    />{% endif %} {% endif %}
    <div style="color: rgba(0, 0, 0, 0.6); margin-top: 4px">
      {{ post.post.likes_count|default:0 }} Likes &#8226; 
      {{ post.post.comments_count|default:0 }} Comments
    </div>

    <div class="feed_inputOptions">
      <div class="inputOption">
        {% if post.is_post_liked %}
        <i style="color: gray; transform: scale(-1, 1)" class="material-icons">
          thumb_up
        </i>
        <h4>Like</h4>
        {% else %}
        <i
          style="color: gray; transform: scale(-1, 1)"
          class="material-icons-outlined"
        >
          thumb_up
        </i>
        <h4>Like</h4>
        {% endif %}
      </div>
      <div class="inputOption">
        <i style="color: gray" class="material-icons-outlined">
          mode_comment
        </i>
        <h4>Comment</h4>
      </div>
      <div class="inputOption">
        <i style="color: gray" class="material-icons-outlined"> shortcut </i>
        <h4>Share</h4>
      </div>
      <div class="inputOption">
        <i
          style="color: gray; transform: rotate(-45deg)"
          class="material-icons"
        >
          send
        </i>
        <h4>Send</h4>
      </div>
    </div>
  </a>
</div>